/**
 * Sync Chatterbox API Types
 *
 * Fetches the OpenAPI spec from the running Chatterbox TTS API and
 * generates TypeScript type definitions using openapi-typescript.
 * The output is written to src/types/chatterbox-api.d.ts.
 *
 * Usage:
 *   CHATTERBOX_API_URL=https://your-api-url npm run sync-api
 *
 * Or with .env file:
 *   npm run sync-api
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import "dotenv/config";
import openapiTS, { astToString } from "openapi-typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** Output path for the generated type definitions. */
const OUTPUT_PATH = path.resolve(__dirname, "../src/types/chatterbox-api.d.ts");

async function main() {
  const apiUrl = process.env.CHATTERBOX_API_URL;

  if (!apiUrl) {
    console.error("Error: CHATTERBOX_API_URL environment variable is required");
    process.exit(1);
  }

  // Fetch the OpenAPI JSON spec from the running API
  const openApiUrl = `${apiUrl}/openapi.json`;
  console.log(`Fetching OpenAPI spec from: ${openApiUrl}`);

  // Parse the OpenAPI spec into a TypeScript AST and convert to source code
  const ast = await openapiTS(new URL(openApiUrl));
  const contents = astToString(ast);

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_PATH);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Prepend a header comment so developers know the file is auto-generated
  const header = `/**
* This file is auto-generated by scripts/sync-api.ts
* Do not edit manually. Run \`npm run sync-api\` to regenerate.
*
* Generated from: ${openApiUrl}
* Generated at: ${new Date().toISOString()}
*/
  `;

  fs.writeFileSync(OUTPUT_PATH, header + contents);
  console.log(`Types written to: ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error("Failed to sync API types:", err);
  process.exit(1);
});